FROM registry.access.redhat.com/ubi9/ubi
RUN dnf update -y && \
    dnf install -y platform-python-pip python3 && \
    pip install prometheus_client cherrypy opentelemetry-distro && \
    dnf clean all

RUN mkdir -p /app
COPY cherrypy_server.py /app
EXPOSE 8080
ENTRYPOINT ["python3"]
CMD ["/app/cherrypy_server.py"]
